name: regression test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install iverilog tcsh
      - name: Run all tests with runtest
        run: |
          cd run
          for f in $(ls ../test); do ../scripts/runtest ../test/$f; done
